export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

export const GET_CATEGORY_BY_NAME_REQUEST = 'GET_CATEGORY_BY_NAME_REQUEST';
export const GET_CATEGORY_BY_NAME_SUCCESS = 'GET_CATEGORY_BY_NAME_SUCCESS';
export const GET_CATEGORY_BY_NAME_FAILURE = 'GET_CATEGORY_BY_NAME_FAILURE';

export const GET_CATEGORY_BY_NAME_AND_PARENT_REQUEST = 'GET_CATEGORY_BY_NAME_AND_PARENT_REQUEST';
export const GET_CATEGORY_BY_NAME_AND_PARENT_SUCCESS = 'GET_CATEGORY_BY_NAME_AND_PARENT_SUCCESS';
export const GET_CATEGORY_BY_NAME_AND_PARENT_FAILURE = 'GET_CATEGORY_BY_NAME_AND_PARENT_FAILURE';
